[package]

name = "drossel"
version = "0.1.0"
authors = [ "Florian Gilcher <florian.gilcher@asquera.de>" ]

[dependencies]

strand          = "0.1.0"
leveldb         = "0.2.0"
drossel-journal = "0.1.1"

[lib]

name = "drossel"
